version: 1
disable_existing_loggers: true
formatters:
  brief:
    format: "%(asctime)s.%(msecs)03d %(levelname)-7s %(process)7d --- [%(name)-12s] %(funcName)-16s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
  standard:
    format: "%(asctime)s.%(msecs)03d %(levelname)-7s %(process)7d --- [%(name)-12s] %(funcName)-16s: %(message)s"
    datefmt: "%Y-%m-%dT%H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    formatter: brief
    level: DEBUG
    stream: ext://sys.stdout
  file:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: standard
    level: INFO
    filename: app.log
    when: D
    interval: 1
    backupCount: 5
  errfile:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: standard
    level: ERROR
    filename: app.error.log
    when: D
    interval: 1
    backupCount: 5
loggers:
  console:
    level: DEBUG
    propagate: true
    handlers: [console]
#  app:
#    level: DEBUG
#    propagate: true
#    handlers: [console, file, errfile]
root:
  level: DEBUG
  propagate: true
  handlers: [console, file, errfile]
