ddns:
  - dns: aliyun
    id: aa
    secret: ss
    domain: example.com
    rr: test
    ttl: 600
    ip_ver: 4

  - dns: dnspod
    id: aa
    secret: ss
    domain: example.com
    rr: test
    ttl: 600
    ip_ver: 4

  - dns: cloudflare
    token: tt
    domain: example.com
    rr: test
    ttl: 600
    ip_ver: 4

wechat:
  # corpid:每个企业都拥有唯一的corpid，获取此信息可在管理后台“我的企业”－“企业信息”下查看“企业ID”（需要有管理员权限）
  # corpsecret:自建应用secret。在管理后台->“应用与小程序”->“应用”->“自建”，点进某个应用，即可看到
  # agentid:每个应用都有唯一的agentid。在管理后台->“应用与小程序”->“应用”，点进某个应用，即可看到agentid
  # 具体不明白的参考企业微信的开发者中心
  corpid: xxx
  secret: xxx
  agentid: 1000002
