name: zabbix-server

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # UTC 01:00 -> CST (China) 09:00, see https://datetime360.com/cn/utc-cst-china-time/
    - cron: '0 1 * * 1' # every monday at 1am
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        image: ['zabbix-server-mysql','zabbix-server-pgsql']
        version: ['ubuntu-5.0-latest','ubuntu-6.0-latest']

    env:
        IMAGE: lightnear/${{ matrix.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            lightnear/${{ matrix.image }}
            ghcr.io/lightnear/${{ matrix.image }}
          flavor: |
            latest=auto
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule,pattern=nightly
            type=ref,event=branch
            type=edge,branch=main
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/') }}
            type=raw,value=${{ matrix.version }},enable=${{ startsWith(github.ref, 'refs/tags/') }}
          labels: |
            maintainer=lightnear

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: edit Dockerfile
        run: |
          sed -i -e 's|FROM.*|FROM zabbix/${{ matrix.image }}:${{ matrix.version }}|' ./zabbix-server/Dockerfile

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./zabbix-server
          platforms: |
            linux/amd64
            linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=lightnear/${{ matrix.image }}:buildcache
          cache-to: type=registry,ref=lightnear/${{ matrix.image }}:buildcache,mode=max
